### ISSUE TITLE
2.0.8 is not compatible with Java7 anymore ?

### ISSUE THREAD

**Issue by normanmaurer** [trustin/jetty-alpn-agent#10]
Seems like after upgrading to 2.0.8 we are not able to run our tests with Java7 anymore in netty:

```
[11:51:58][io.netty:netty-common] Exception in thread "main" java.lang.UnsupportedClassVersionError: org/mortbay/jetty/alpn/agent/Premain : Unsupported major.minor version 52.0
[11:51:58][io.netty:netty-common]  at java.lang.ClassLoader.defineClass1(Native Method)
[11:51:58][io.netty:netty-common]  at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[11:51:58][io.netty:netty-common]  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[11:51:58][io.netty:netty-common]  at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[11:51:58][io.netty:netty-common]  at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[11:51:58][io.netty:netty-common]  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[11:51:58][io.netty:netty-common]  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[11:51:58][io.netty:netty-common]  at java.security.AccessController.doPrivileged(Native Method)
[11:51:58][io.netty:netty-common]  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[11:51:58][io.netty:netty-common]  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[11:51:58][io.netty:netty-common]  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[11:51:58][io.netty:netty-common]  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[11:51:58][io.netty:netty-common]  at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:300)
[11:51:58][io.netty:netty-common]  at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
[11:51:58][io.netty:netty-common] FATAL ERROR in native method: processing of -javaagent failed
[11:51:59][io.netty:netty-common] /bin/sh: line 1: 18558 Aborted /opt/jdk/1.7/bin/java -server -dsa -da -ea:io.netty... -Xmx2048m -XX:MaxDirectMemorySize=2048m -XX:+UseCompressedOops -XX:+AggressiveOpts -XX:+TieredCompilation -XX:+UseBiasedLocking -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails '-javaagent:/var/lib/teamcity-agent/.m2/repository/org/mortbay/jetty/alpn/jetty-alpn-agent/2.0.8/jetty-alpn-agent-2.0.8.jar=${jetty.alpnAgent.option}' -D_ -D_ -D_ -D_ -jar /opt/teamcity-agent/work/9fb9a58aa23c687/common/target/surefire/surefirebooter8122862787386978848.jar /opt/teamcity-agent/work/9fb9a58aa23c687/common/target/surefire/surefire3618297481844495650tmp /opt/teamcity-agent/work/9fb9a58aa23c687/common/target/surefire/surefire_01407380808978501630tmp
[11:51:59][io.netty:netty-common] 
```

**Comment by sbordet** [comment]
Doh! I don't know why I have updated the POM to require JDK 8 after 2.0.7. Will release 2.0.9.

**Comment by normanmaurer** [comment]
@sbordet thanks a lot!

**Comment by sbordet** [comment]
@normanmaurer 2.0.9 on its way to Maven Central.

**Comment by normanmaurer** [comment]
@sbordet <3
